### ISSUE TITLE
font size of others elements get overrided

### ISSUE THREAD

**Issue by Upd4ting** [nstudio/nativescript-checkbox#133]
Hey there.

It appears that when using a `CheckBox`  into my page my `Label` that are at the bottom of the `CheckBox` have their fontSize override to `14`. Elements above the `CheckBox` aren't overrided.

Any idea?

**Comment by stephaneQ2** [comment]
I am having the same issue on NS 7. Please let me know how we can resolve this.

**Comment by Upd4ting** [comment]
It appears that it's because of the `fontSizeProperty` that he declares as `CssProperty` into his android implementation. 
I've done a patch-package for that in waiting of a fix by the author.

**Comment by boris01** [comment]
@Upd4ting, @stephaneQ2, this plugin is now managed in another repo: https://github.com/nstudio/nativescript-plugins
I opened an issue there regarding the same problems, https://github.com/nstudio/nativescript-plugins/issues/1
The issue is fixed now.
Try 2.0.4 version from the NPM, https://www.npmjs.com/package/@nstudio/nativescript-checkbox

**Comment by Upd4ting** [comment]
@boris01 Thanks for letting us know!
